"""
描述: Agent 工具注册与管理
主要功能:
    - BaseTool 基类定义
    - ToolRegistry 工具注册表
    - 工具注册装饰器
依赖: pydantic
"""

from __future__ import annotations

from abc import ABC, abstractmethod
import logging
from typing import Any, Type

from pydantic import BaseModel, Field


# ============================================
# region BaseTool
# ============================================
class BaseTool(BaseModel, ABC):
    """
    工具基类
    
    所有具体的工具都应继承此类，并实现 run 方法。
    Pydantic 模型用于定义工具的输入参数 schemas。
    """
    name: str = Field(..., description="工具名称 (英文标识符)")
    description: str = Field(..., description="工具描述 (用于 Agent 决策)")

    @abstractmethod
    def run(self, **kwargs: Any) -> Any:
        """
        执行工具逻辑
        """
        pass

    @classmethod
    def get_schema(cls) -> dict[str, Any]:
        """
        获取工具的参数 Schema (Auto-generated by Pydantic)
        """
        schema = cls.model_json_schema()
        # 移除 name 和 description，因为它们不是调用时的参数
        properties = schema.get("properties", {}).copy()
        if "name" in properties:
            del properties["name"]
        if "description" in properties:
            del properties["description"]
        
        required = schema.get("required", []).copy()
        if "name" in required:
            required.remove("name")
        if "description" in required:
            required.remove("description")

        return {
            "name": cls.model_fields["name"].default,
            "description": cls.model_fields["description"].default,
            "parameters": {
                "type": "object",
                "properties": properties,
                "required": required,
            },
        }
# endregion
# ============================================


# ============================================
# region ToolRegistry
# ============================================
class ToolRegistry:
    """
    工具注册表 (单例)
    """
    _tools: dict[str, Type[BaseTool]] = {}

    logger = logging.getLogger(__name__)

    @classmethod
    def register(cls, tool_cls: Type[BaseTool]) -> Type[BaseTool]:
        """
        注册工具类
        """
        try:
            name = tool_cls.model_fields["name"].default
            if not isinstance(name, str) or not name:
                cls.logger.error("Tool name is invalid: %s", tool_cls)
                return tool_cls

            cls._tools[name] = tool_cls
        except Exception as exc:
            cls.logger.error("Failed to register tool: %s", tool_cls, exc_info=exc)
        return tool_cls

    @classmethod
    def get_tool(cls, name: str) -> Type[BaseTool] | None:
        """
        获取工具类
        """
        return cls._tools.get(name)

    @classmethod
    def get_all_tools(cls) -> dict[str, Type[BaseTool]]:
        """
        获取所有已注册工具
        """
        return cls._tools

    @classmethod
    def get_all_schemas(cls) -> list[dict[str, Any]]:
        """
        获取所有工具的 Schema 定义 (用于 System Prompt)
        """
        schemas = []
        for tool_cls in cls._tools.values():
            try:
                schemas.append(tool_cls.get_schema())
            except Exception as exc:
                cls.logger.error("Failed to build tool schema: %s", tool_cls, exc_info=exc)
        return schemas

# 装饰器别名
register_tool = ToolRegistry.register
# endregion
# ============================================
